# Generated by Django 4.2.7 on 2025-06-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('pack_type', models.CharField(max_length=50)),
                ('ppg', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('sales_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'retail_data',
                'indexes': [models.Index(fields=['year'], name='retail_data_year_8b0c18_idx'), models.Index(fields=['brand'], name='retail_data_brand_85dbca_idx'), models.Index(fields=['pack_type'], name='retail_data_pack_ty_f63df9_idx'), models.Index(fields=['channel'], name='retail_data_channel_e3931a_idx')],
            },
        ),
    ]
